# Generated by Django 4.2.3 on 2023-07-28 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary_model',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
